# Generated by Django 5.1.1 on 2024-10-08 07:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='apps/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('CM', 'COMMERCIAL'), ('SM', 'SOCIAL'), ('ED', 'EDUCATIONAL'), ('OT', 'OTHER')], max_length=2)),
            ],
        ),
    ]
